name: ci-algorithms-and-data-structures-workflow
# on: [pull_request] # push, pull_request
on:
  pull_request:
    branches:
      - development
      - master
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersions: ['16.8.0']

    steps:
      - uses: actions/checkout@v2 # baixa os arquivos na máquina
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodeVersions }}
      - run: npm install
      - run: npm run test
      - run: echo "Tests passed"
      - run: cat ./coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: bernardomoraes/algorithms:latest